#!/bin/sh
# filename: config
LDAPADDCMD="/usr/bin/ldapadd"
LDAPDELCMD="/usr/bin/ldapdelete"
KDCADDCMD="/usr/bin/kadmin"
KDCADMPRINC="xxx"
KDCADMPWD="yyy"
SLAPPASSWORD="/usr/sbin/slappasswd"
#SECRET="/root/ldap/secret" # Put your password in this file. We recommend making it readable just by root.
#LDAPPASS=`cat $SECRET`
LDAPPASS="yyy"
LDAPUSERSUX="ou=People,dc=xxx,dc=local"
LDAPGROUPSUX="ou=group,dc=xxx,dc=local"
LDAPROOTSUX="dc=xxx,dc=local"
#################  >>>>>>
HDFSKDCPRINC="xxx"
HDFSKDCPWD="yyy"
SCRIPTDIR="/home/hdfs/ldap"
################# <<<<<<<
HOMEDIR="/home"
SKEL="/etc/skel"
TMP="."
UNIT="People"
ORG="com"
DOMAIN="xxx.com.tw"
GROUP="Group"
MODDATE=`date "+%Y%m%d%H%M%S.%N"`
ARCHIVE=".deleted"